server:
  port: 8080 
spring:
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
    converters:
      preferred-json-mapper: gson
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/myWebsite?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true&zeroDateTimeNehavior=convertToNull
    username: freestyle385
    password: freestyle385
